Improve optimization functionality
MycroftAI/mycroft-precise pull request #151
Opened 2020-04-23 14:35 UTC by MatthewScholefield

Models cost more accurately by taking into account ambient activations and minimizing the combination between ambient activations and false negatives. The docstrings in the new module describe how this combination is estimated and the assumptions that are made.

2020-04-29 13:06 UTC, forslund requested changes
I think it looks good, just a tiny nitpick in the license header that needs to be changed.

Should the run method have a docstring that describes the process and perhaps flag that people can look up the tree_structured_parzen_estimator if they're interested in how the hyper parameters are optimized (if I understood things correctly)
I don't quite remember what was said at the meeting, should a test be added to verify the annoyance estimator?

2020-04-29 13:06 UTC, forslund commented on precise/annoyance_estimator.py
> +# Copyright 2019 Mycroft AI Inc.
2020 right?

2020-04-30 09:15 UTC, MatthewScholefield commented on precise/annoyance_estimator.py
> +# Copyright 2019 Mycroft AI Inc.
Good catch, just changed.

2020-05-04 12:19 UTC, forslund approved these changes

2020-05-04 12:19 UTC, merged